---
# tasks file for opdk-setup-postgres-master
- name: Postgres replication master
  shell: '{{ apigee_service }} apigee-postgresql setup-replication-on-master -f {{ opdk_installation_config_file }}'

- name: Validate postgres replication master
  shell: '{{ apigee_service }} apigee-postgresql postgres-check-master'
